version: '3.4'

networks:
  identity-network:
    name: identity-network
    driver: bridge

services:
  identity-core-api:
    build: Identity/
    restart: always
    networks: 
      - identity-network
    ports:
      - 80:80
    depends_on:
      - identity-core-db

  identity-core-db:
    image: postgres:latest
    networks: 
      - identity-network
    ports:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity-core
    volumes:
      - identity-postgres-data:/var/lib/postgres

volumes:
  identity-postgres-data:

    